common/models/Dispute.php
<?php
namespace common\models;


use yii\db\ActiveRecord;

/**
 * Class Dispute
 * @package common\models
 *
 * @property $id int
 * @property $client_chat_id int
 * @property $expert_chat_id int
 * @property $order_id int
 * @property $dial_chat_id int
 * @property $client_id int
 * @property $expert_id int
 * @property $status int
 * @property $client_appeal_id int
 * @property $expert_appeal_id int
 * @property $clientChat common\models\Chat
 * @property $expertChat Chat
 * @property $dialChat Chat
 * @property $clientAppeal Appeal
 * @property $expertAppeal Appeal
 * @property $dial_id int
 *
 *
 */
class Dispute extends ActiveRecord{

    const STATUS_OPEN = 1;
    const STATUS_CLOSED = 2;

    const DECISION_CONTINUE_DIAL = 1;
    const DECISION_CLOSE_DIAL = 2;
    const DECISION_CANCEL_DIAL = 3;


    /**
     * @return string
     */
    public static function tableName()
    {
        return 'dispute';
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClient(){
        return $this->hasOne(User::class,['id' => 'client_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getExpert(){
        return $this->hasOne(User::class,['id' => 'expert_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDial(){
        return $this->hasOne(Dial::class,['id' => 'dial_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClientChat(){
        return $this->hasOne(Chat::class,['id' => 'client_chat_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getExpertChat(){
        return $this->hasOne(Chat::class,['id' => 'expert_chat_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDialChat(){
        return $this->hasOne(Chat::class,['id' => 'dial_chat_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClientAppeal(){
        return $this->hasOne(Appeal::class,['id' => 'client_appeal_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getExpertAppeal(){
        return $this->hasOne(Appeal::class,['id' => 'expert_appeal_id']);
    }

}

backend/controllers/ClientController.php
<?php
/**
 * Created by PhpStorm.
 * User: hustler
 * Date: 19.06.2019
 * Time: 21:43
 */

namespace backend\controllers;

use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\User;
use yii\base\Exception;
use yii\web\NotFoundHttpException;

class ClientController extends Controller
{
    public $defaultAction = 'settings';


    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['editUsers'],
                    ],
                ],
            ],
        ];
    }


    public function actionOrders($id){
        $client = User::findOne($id);
        return $this->render('orders', [
            'client' => $client,
            'orders' => $client->orders
        ]);
    }

    /**
     * @param $id
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionSettings($id){

        $user = User::findOne($id);
        if(!$user)
            throw new NotFoundHttpException("Не найден пользователь");

        if(!$user->can('Клиент'))
            throw new NotFoundHttpException("Неверный тип пользователя");

        $user->scenario = User::SCENARIO_CLIENT_SETTINGS;
        if($user->load(\Yii::$app->request->post(),'')){
            if($user->save()){
                if($user->can('Клиент')) {
                    $controller = 'client';
                    $flashKey = 'client-settings';
                }
                if($user->can('Эксперт')) {
                    $controller = 'expert';
                    $flashKey = 'client-settings';
                }
                if($user->can('Администратор')) {
                    $controller = 'users/edit';
                    $flashKey = 'saving-report';
                }

                $this->setFlash($flashKey, 'success', 'Успешно сохранено');
                return $this->redirect([ "/$controller" , 'id' => $user->id]);
            }
        }

        $roles = \Yii::$app->authManager->getRoles();
        $socials = \Yii::$app->oauth->socials;

        return $this->render('settings', [
            'client' => $user,
            'roles' => $roles,
            'socials' => $socials
        ]);
    }

    private function setFlash($key,$status, $message){
        \Yii::$app->session->setFlash($key, [ 'status' => $status, 'message' => $message ]);
    }

    /**
     * @param $id
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionInfo($id){
        $client = User::findOne($id);
        if(!$client) throw new NotFoundHttpException("Не найден пользователь");
        $client->scenario = User::SCENARIO_CLIENT_INFO;
        if($client->load(\Yii::$app->request->post(),'')){
            $client->save(false);
            $this->setFlash('info', 'success', 'Успешно сохранено');
            return $this->refresh();
        }

        return $this->render('info', ['client' => $client]);
    }




}

frontend/controllers/ClientController.php
<?php

namespace frontend\controllers;

use common\helpers\UserHelper;
use common\models\Appeal;
use common\models\Card;
use common\models\Chat;
use common\models\Dial;
use common\models\Dispute;
use common\notifications\Notification;
use common\models\NotificationsSettings;
use common\models\Order;
use common\models\User;
use common\models\UserPackage;
use common\notifications\NotificationType;
use frontend\models\ClientSettings;
use Yii;
use yii\base\InvalidArgumentException;
use yii\db\Query;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\web\Response;
use yii\web\ServerErrorHttpException;
use yii\web\UploadedFile;

/**
 * Orders controller
 */
class ClientController extends Controller
{

    public $defaultAction = 'current';
    /**
     * .
     *
     * @return mixed
     */
    public function actionCurrent() {
        /** @var User $user */
        $user = \Yii::$app->user->identity;
        $orders = $user->getOrders()->andWhere(['status' => Order::STATUS_WORK])->all();
        return $this->render('//lk/client/current', ['client' => $user, 'orders' => $orders ]);
    }


    public function actionImage(){

        \Yii::$app->response->format = Response::FORMAT_JSON;

        /** @var User $user */
        $user = \Yii::$app->user->identity;
        $file = UploadedFile::getInstanceByName('image');

        $upload_dir = \Yii::getAlias('@uploads') . '/users/' . $user->id;
        if(!file_exists($upload_dir))
            mkdir($upload_dir);
        $filename = uniqid() . time() . '.' . $file->extension;
        $fullname = "$upload_dir/$filename";
        $file->saveAs($fullname);

        if($user->photo){
            $existing_filename = $upload_dir . '/' . $user->photo;
            if(file_exists($existing_filename)){
                unlink($existing_filename);
            }
        }

        $user->photo = $filename;
        $user->save(false);
        return ['imageSource' => $user->getAvatar() ];
    }

    public function actionSearch()
    {
        /** @var User $user */
        $user = \Yii::$app->user->identity;
        $orders = $user->getOrders()->andWhere(['status' => [ Order::STATUS_FREE, Order::STATUS_WAITING_RESERVATION ]])->all();
        $safeDialEnabled = $user->card ? true : false ;
        return $this->render('//lk/client/search', ['client' => $user, 'orders' => $orders, 'safeDialEnabled' => $safeDialEnabled]);
    }

    public function actionCompleted()
    {
        /** @var User $client */
        $client = \Yii::$app->user->identity;
        $orders = Order::findAll(['client_id' => $client->id, 'status' => Order::STATUS_CLOSED ]);
        return $this->render('//lk/client/completed', ['orders' => $orders, 'client' => $client]);
    }

    public function actionDisputes(){

        /** @var User $client */
        $client = \Yii::$app->user->identity;
        $disputes = Dispute::findAll(['client_id' => $client->id, 'status' => Dispute::STATUS_OPEN]);
        return $this->render('//lk/client/disputes', ['disputes' => $disputes]);

    }

    /**
     * @param $id
     * @return string
     * @throws BadRequestHttpException
     */
    public function actionDispute($id){
        $user = \Yii::$app->user->identity;

        if(!$dispute = Dispute::findOne($id))
            throw new BadRequestHttpException("Неверный параметр");

        $chat = $dispute->clientChat;

        return $this->render('//lk/client/dispute', ['dispute' => $dispute, 'chat' => $chat, 'user' => $user ]);
    }


    /**
     * @return string
     */
    public function actionCards(){
        /** @var User $user */
        $user = \Yii::$app->user->identity;
        $cards = Card::findAll(['user_id' => $user->id]);
        return $this->render('//lk/client/settings-cards', [
            'user' => $user,
            'cards' => $cards
        ]);
    }




    /**
     * @return string|Response
     */
    public function actionSettings()
    {
        $user = \Yii::$app->user->identity;

        $model = new ClientSettings();
        if($model->load(\Yii::$app->request->post(),'')){
            if($model->save()){
                Notification::send('your_info_changed',['target_user' =>  $model->_user->id]);
                return $this->refresh();
            }
        }

        $cities = (new Query())->select(['id', 'name'])->from('city')->all();
        $socials = \Yii::$app->oauth->socials;
        return $this->render('//lk/client/settings', [
            'model' => $model,
            'user' => $user,
            'cities' => $cities,
            'socials' => $socials
        ]);
    }

    /**
     * @return string
     */
    public function actionContacts()
    {
        $user = \Yii::$app->user->identity;
        return $this->render('//lk/client/contacts', ['expert' => $user]);
    }

    /**
     * @return string
     */
    public function actionNotices()
    {
        $user = \Yii::$app->user->identity;
        $notifications = $user->notifications;
        return $this->render('//lk/client/notices', ['notifications' => $notifications ]);
    }

    /**
     * @return string|Response
     */
    public function actionNoticesoptions()
    {
        /** @var User $user */
        $user = \Yii::$app->user->identity;
        $settings = $user->notificationSettings;

        $descriptions = NotificationType::find()->select('name,description')->asArray()->all();
        $descriptions = ArrayHelper::map($descriptions, 'name', 'description');

        $settings->scenario = NotificationsSettings::SCENARIO_CLIENT;
        if($settings->load(\Yii::$app->request->post(),'')){
            $settings->save(false);
            return $this->refresh();
        }
        return $this->render('//lk/client/noticesoptions', ['settings' => $settings, 'descriptions' => $descriptions ,  'client' => $user] );
    }

    /**
     * @return string
     */
    public function actionExperts()
    {
        /** @var User $user */
        $user = \Yii::$app->user->identity;
        $experts = $user->favorites;
        return $this->render('//lk/client/choosen', [
            'client' => $user,
            'experts' => $experts
        ]);
    }

    public function actionCancel($order_id){
        $order = Order::findOne($order_id);
        \Yii::$app->orderService->cancelOrder($order);
    }
}

frontend/views/lk/client/appeal.php
<?php
/** @var $this \yii\web\View */
/** @var $appeal \common\models\Appeal */


use yii\helpers\Url;

?>

<main class="lk">
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breads_wrapper dark">
                        <ul>
                            <li><a href="/">Главная</a></li>
                            <li><span>></span></li>
                            <li><span>Личный кабинет</span></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <?php $menu = 'orders'; include __DIR__ . '/left-sidebar.php' ?>
                </div>
            </div>
            <div class="col-md-9">
                <div class="lk_user_body">

                    <?= $this->render('my-orders-tabs') ?>


                    <div class="lk_expert_body_packejes_tabs_body">

                        <h3>Создание жалобы</h3>




                        <div>




                            <form action="<?= Url::to(['/dispute/appeal', 'dial_id' => $appeal->dial_id]) ?>" method="post">
                                <input type="hidden" name="dial_id" value="<?= $appeal->dial_id ?>">

                                <div class="f_group">
                                    <label for="content">Текст жалобы</label>
                                    <textarea name="content" id="content" cols="30" rows="10"><?= $appeal->content ?></textarea>
                                </div>



                                <?php if($appeal->hasErrors('content')): ?>
                                <p><?= $appeal->getFirstError('content') ?></p>
                                <?php endif; ?>

                                <button>Отправить</button>
                            </form>
                        </div>



                    </div>
                </div>
            </div>
        </div>
    </div>

</main>

frontend/views/lk/client/completed.php
<?php
/** @var $orders array */
/** @var $client \common\models\User */
/** @var $this \yii\web\View */


use yii\helpers\Url;

?>

<main class="lk">
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breads_wrapper dark">
                        <ul>
                            <li><a href="/">Главная</a></li>
                            <li><span>></span></li>
                            <li><span>Личный кабинет</span></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <?php $menu = 'orders'; include __DIR__ . '/left-sidebar.php' ?>
                </div>
            </div>
            <div class="col-md-9">
                <div class="lk_user_body">

                    <?= $this->render('my-orders-tabs') ?>


                    <div class="lk_expert_body_packejes_tabs_body">
                        <div class="lk_user_body_chat_closed">
                            <?php if(count($orders) == 0) echo "Нет завершенных заказов" ?>
                            <?php foreach($orders as $order):
                                /** @var $order \common\models\Order */
                                $client = $order->client;
                                $expert = $order->expert;
                                ?>
                            <div class="content_last_closed_item">
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="content_last_closed_item_img">
                                            <div class="content_last_closed_item_img_string">
                                                <img src="/img/icons/types/icon_car.png" alt="">
                                                <div class="content_last_closed_item_img_string_span"><?= $order->typeLabel() ?></div>
                                            </div>
                                            <div class="content_last_closed_item_img_string_img" style="background-image: url('<?= Url::to('@web/img/icons/main_top/icon3_h.png') ?>'"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-9">
                                        <div class="content_last_closed_item_body_top"><?= $order->nameLabel() ?></div>
                                        <div class="content_last_closed_item_body_subtop">
                                            <div class="row">
                                                <div class="col-md-4 col-sm-6">
                                                    <div class="content_last_closed_item_body_subtop_top">Марка</div>
                                                    <div class="content_last_closed_item_body_subtop_bot"><?= $order->model->name ?></div>
                                                </div>
                                                <div class="col-md-4 col-sm-6">
                                                    <div class="content_last_closed_item_body_subtop_top">Срок подбора</div>
                                                    <div class="content_last_closed_item_body_subtop_bot"><?= $order->period_to ?> дня</div>
                                                </div>
                                                <div class="col-md-4 col-sm-6">
                                                    <div class="content_last_closed_item_body_subtop_top">Стоимость</div>
                                                    <div class="content_last_closed_item_body_subtop_bot bold"><?= $order->dial->reward ?></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="content_last_closed_item_body_content">
                                            <?= $order->comment ?>
                                        </div>
                                        <div class="content_last_closed_item_body_footer">
                                            <div class="row align-middle">
                                                <div class="col-md-6 text-left">
                                                    <div class="content_last_closed_item_body_footer_img" style="background-image: url(<?= $order->expert->avatar ?>);">
                                                        <a href=""></a>
                                                    </div>
                                                    <span class="content_last_closed_item_body_footer_span">
                                                Эксперт: <span><a style="color: black" href="<?= $order->expert->profileUrl ?>"><?= ucfirst($order->expert->family) . ' ' . ucfirst($order->expert->firstname) ?></a></span>
                                            </span>
                                                </div>
                                                <div class="col-md-6 text-right">
                                                    <div class="content_last_closed_item_body_footer_span_r">
                                                        <a href="#" class="content_last_closed_item_body_footer_span_r_openclose">
                                                            <span>Скрыть отзывы о сделке</span>
                                                            <span>Посмотреть отзывы о сделке</span>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <?php $reviews = $order->reviewsSorted ?>
                                <div class="content_last_closed_item_sub">
                                    <div class="row">

                                        <div class="col-md-6">
                                            <div class="content_reviews_item_header clearfix">
                                                <div class="content_reviews_item_header_img" style="background-image: url('<?= $client->avatar ?>')">
                                                    <a href="<?= $client->getProfileUrl() ?>"></a>
                                                </div>
                                                <div class="content_reviews_item_header_text">
                                                    <div class="content_reviews_item_header_text_label lab1">Заказчик</div>
                                                    <div class="content_reviews_item_header_text_text"><?= $client->family . ' ' . $client->firstname ?></div>
                                                </div>
                                            </div>
                                            <?php if(empty($reviews['client'])): ?>
                                            <div class="content_last_closed_item_sub_rev">
                                                <div class="content_last_closed_item_sub_rev_no_rev">
                                                    Заказчик не оставил отзыв
                                                </div>
                                            </div>
                                            <?php else:
                                                /** @var $review \common\models\Review*/
                                                $review = $reviews['client'];  ?>
                                                <div class="content_last_closed_item_sub_rev">
                                                    <div class="content_last_closed_item_sub_rev_rev">
                                                        <div class="content_last_closed_item_sub_rev_rev_body"><?= $review->content ?></div>
                                                        <div class="content_last_closed_item_sub_rev_rev_date"><?= $review->getDate("d.m.y") ?></div>
                                                    </div>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="content_reviews_item_header clearfix">
                                                <div class="content_reviews_item_header_img" style="background-image: url('<?= $expert->avatar ?>')">
                                                    <a href="<?= $expert->getProfileUrl() ?>"></a>
                                                </div>
                                                <div class="content_reviews_item_header_text">
                                                    <div class="content_reviews_item_header_text_label lab2">Эксперт</div>
                                                    <div class="content_reviews_item_header_text_text"><?= $expert->family . ' ' . $expert->firstname ?></div>
                                                </div>
                                            </div>
                                            <?php if(empty($reviews['expert'])): ?>
                                            <div class="content_last_closed_item_sub_rev">
                                                <div class="content_last_closed_item_sub_rev_no_rev">
                                                    Эксперт не оставил отзыв
                                                </div>
                                            </div>
                                            <?php else:
                                            /** @var $review \common\models\Review*/
                                            $review = $reviews['expert'];  ?>
                                            <div class="content_last_closed_item_sub_rev">
                                                <div class="content_last_closed_item_sub_rev_rev">
                                                    <div class="content_last_closed_item_sub_rev_rev_body"><?= $review->content ?></div>
                                                    <div class="content_last_closed_item_sub_rev_rev_date"><?= $review->getDate("d.m.y") ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>



                            </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</main>

frontend/views/lk/client/contacts.php
<?php
/** @var $this \yii\web\View */
/** @var $client \common\models\User */
use yii\helpers\Url;

?>
<main class="lk">
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breads_wrapper dark">
                        <ul>
                            <li><a href="/">Главная</a></li>
                            <li><span>></span></li>
                            <li><span>Личный кабинет</span></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <?php $menu = 'contacts'; include __DIR__ . '/left-sidebar.php' ?>
                </div>
            </div>
            <div class="col-md-9">
                <div class="lk_expert_body">
                    <div class="lk_expert_body_general">
                        <div class="lk_expert_body_general_top">
                            <?= $client->family . ' ' . $client->firstname . ' ' . $client->lastname ?>
                        </div>
                        <div class="lk_expert_body_general_body">
                            <div class="lk_left_body_info_body">
                                <ul>
                                    <li>Город:   <span><?= $client->city->name ?></span></li>
                                    <li>Возраст:   <span><?= $client->age ? $client->age . ' лет' : 'не указан' ?></span></li>
                                    <?php
                                    $icon = $client->confirmed_phone ? Url::to('@web/img/icons/steps/ok.jpg') : Url::to('@web/img/icons/steps/nok.png');
                                    $label = $client->confirmed_phone ? "Проверенный телефон" : "Телефон не проверен";
                                    ?>
                                    <li>
                                        <img src="<?= $icon ?>" alt=""> <?= $label ?>:   <span><?= $client->phone ?></span>
                                    </li>
                                </ul>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</main>

frontend/views/lk/client/dispute.php
<?php
/** @var $this \yii\web\View */
/** @var $dispute \common\models\Dispute */
/** @var $user \common\models\User */
/** @var $chat \common\models\Chat */


use yii\helpers\Url;
use frontend\assets\NiceScrollAsset;
use frontend\assets\ChatAsset;

NiceScrollAsset::register($this);
ChatAsset::register($this);

?>

<main class="lk">
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breads_wrapper dark">
                        <ul>
                            <li><a href="/">Главная</a></li>
                            <li><span>></span></li>
                            <li><span>Личный кабинет</span></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <?php $menu = 'orders'; include __DIR__ . '/left-sidebar.php' ?>
                </div>
            </div>
            <div class="col-md-9">
                <div class="lk_user_body">

                    <?= $this->render('my-orders-tabs') ?>


                    <div class="lk_expert_body_packejes_tabs_body">

                        <?php if($appeal = $dispute->clientAppeal): ?>



                        <h3>Текст обращения</h3>
                        <p>
                            <?= $appeal->content ?>
                        </p>
                        <?php endif; ?>

                        <br>

                        <div id="chat">



                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

</main>
<?php

$chat_id = $chat->id;
$user_id = $user->id;

$sendUrl = Url::to(['/chat/post']);
$updateUrl = Url::to(['/chat/get']);

$script = <<< JS
let container = $('#chat');
    
$(container).OpenChat({
    id: $chat_id,
    user: $user_id,
    sendUrl: '$sendUrl',
    updateUrl:'$updateUrl'
});

JS;

$this->registerJs($script);

frontend/views/lk/client/disputes.php
<?php
/** @var $this \yii\web\View */
/** @var $disputes array */


use yii\helpers\Url;

?>

<main class="lk">
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breads_wrapper dark">
                        <ul>
                            <li><a href="/">Главная</a></li>
                            <li><span>></span></li>
                            <li><span>Личный кабинет</span></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <?php $menu = 'orders'; include __DIR__ . '/left-sidebar.php' ?>
                </div>
            </div>
            <div class="col-md-9">
                <div class="lk_user_body">

                    <?= $this->render('my-orders-tabs') ?>

                    <div class="lk_expert_body_packejes_tabs_body">

                        <h3>Все жалобы</h3>

                        <div>
                            <?php foreach($disputes as $dispute): /** @var $appeal \common\models\Appeal */ ?>
                            тут что-то написано<br>
                            <a href="<?= Url::to(['lk/dispute', 'id' => $dispute->id ]) ?>">Перейти к спору</a>
                            <?php endforeach; ?>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

</main>