common/models/Group.php
<?php
/**
 * Created by PhpStorm.
 * User: hustler
 * Date: 25.03.2019
 * Time: 21:49
 */

namespace common\models;

use yii\db\ActiveRecord;

/**
 * Class Group
 * @package common\models
 *
 * @property int  $id
 * @property string  $name
 */
class Group extends ActiveRecord
{
    /**
     * @return string
     */
    public static function tableName()
    {
        return 'groups';
    }

    public function rules()
    {
        return [
            [['name'], 'required']
        ];
    }


}

backend/controllers/GroupsController.php
<?php

namespace backend\controllers;

use Yii;
use yii\base\Exception;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use common\models\Group;
use yii\filters\AccessControl;
use yii\web\Response;


class GroupsController extends Controller{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['accessGroups'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['edit', 'add', 'save', 'delete', 'batch'],
                        'roles' => ['editGroups'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex(){
        $data = Group::find()->all();
        return $this->render('list', ['groups' => $data]);
    }

    public function actionEdit($id){
        $group = Group::findOne($id);
        return $this->render('edit', ['group' => $group ]);
    }

    public function actionAdd(){
        $group = new Group();
        return $this->render('edit', ['group' => $group ]);
    }

    public function actionSave(){

        if($id = Yii::$app->request->post('id')){
            if(!$group = Group::findOne($id))
                throw new Exception("Не найден указанный пользователь");
        } else {
            $group = new Group();
        }

        if($group->load(Yii::$app->request->post(), '')){
            if($group->validate())
            {
                $group->save(false);
                \Yii::$app->session->setFlash('saving-report', ['success' => true, 'message' => 'Успешно сохранено']);
                return $this->redirect(['edit', 'id' => $group->id]);
            }
        }
        return $this->render('edit', ['group' => $group]);
    }


    public function actionDelete($id){

        try{
            if(!$group = Group::findOne($id))
                throw new \Exception('Не найдена указанная группа');

            $group->delete();
            \Yii::$app->session->setFlash('operation-report', ['success' => true, 'message' => "Успешно удалено" ]);
        } catch(\Exception $e){
            \Yii::$app->session->setFlash('operation-report', ['success' => false, 'message' => $e->getMessage() ]);
        }

        return $this->redirect(['/groups']);

    }

    public function actionBatch(){

        $request = \Yii::$app->request;

        $ids = json_decode($request->post('ids'));
        $ids = array_map('intval', $ids);
        $action = $request->post('action');

        try{
            if($action == 'delete')
            {
                $groups = Group::findAll(['id' => $ids]);

                foreach($groups as $group){
                    $group->delete();
                }

                \Yii::$app->session->setFlash('operation-report', ['success' => true, 'message' => "Группы удалены" ]);
            }

        } catch (Exception $e){
            \Yii::$app->session->setFlash('operation-report', ['success' => false, 'message' => $e->getMessage() ]);
        }

        return $this->redirect(['index']);
    }

}

backend/views/groups/edit.php
<?php

/* @var $this yii\web\View */
/* @var $group \common\models\Group */

use yii\web\View;
use yii\helpers\Url;
use backend\assets\DateRangeAsset;
use backend\assets\InputmaskAsset;
use common\models\Role;
use common\models\Group;
use yii\helpers\ArrayHelper;

?>

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Добавить группу
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Главная</a></li>
            <li><a href="#">Группы</a></li>
            <li class="active"><?= $group->id ? "Редактировать группу" : "Добавить группу" ?></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <?php if($report = Yii::$app->session->getFlash('saving-report')): ?>
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4>	<i class="icon fa fa-check"></i> <?= $report['message'] ?></h4>
            </div>
        <?php endif; ?>

        <div class="box">
            <form class="form-horizontal" action="<?= Url::toRoute('/groups/save') ?>" method="post">
                <input type="hidden" name="id" value="<?= $group->id ?>">
                <div class="box-body">

                    <?php if($group->hasErrors('name')): ?>
                        <div class="form-error"><?= $group->getFirstError('name') ?></div>
                    <?php endif; ?>
                    <div class="form-group">
                        <label for="family" class="col-sm-2 control-label">Название</label>
                        <div class="col-sm-10">
                            <input name="name" type="text" class="form-control" placeholder="Название группы" value="<?= $group->name ?>">
                        </div>
                    </div>

                </div><!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-info">Сохранить</button>
                </div>
            </form>
        </div><!-- /.box -->

    </section><!-- /.content -->

backend/views/groups/list.php
<?php

/* @var $this yii\web\View */
/* @var array $data */

$this->title = 'Группы';

use \yii\web\View;
use backend\assets\DataTablesAsset;
use backend\assets\InputmaskAsset;
use backend\assets\DateRangeAsset;
use yii\helpers\Url;
use backend\assets\DialogAsset;

DataTablesAsset::register($this);
DateRangeAsset::register($this);
InputmaskAsset::register($this);
DialogAsset::register($this);

?>

    <?= $this->render('//modals/dialog') ?>

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Группы
        </h1>
        <ol class="breadcrumb">
            <li><a href="<?php echo Url::to(['/dashboard']) ?>"><i class="fa fa-dashboard"></i> Главная</a></li>
            <li class="active">Группы</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <?php if($report = Yii::$app->session->getFlash('operation-report')): ?>
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4>	<i class="icon fa fa-check"></i> <?= $report['message'] ?></h4>
            </div>
        <?php endif; ?>

        <div class="row">
            <div class="col-xs-12">

                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Список групп</h3>
                    </div>
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" id="check_all" style="cursor: pointer">
                                        </label>
                                    </div>
                                </th>
                                <th>Название группы</th>
                                <th>Действия</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($groups as $group): /** @var $group \common\models\Group */?>
                                <tr>
                                    <td>
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" style="cursor: pointer" value="<?= $group->id ?>">
                                            </label>
                                        </div>
                                    </td>
                                    <td><?= $group->name ?></td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <div class="btn-group btn-group-sm">
                                                <a href="<?= Url::to(['/groups/edit', 'id' => $group->id ]) ?>" class="btn btn-success"><i class="fa fa-edit"></i></a>
                                                <a href="<?= Url::to(['/groups/delete', 'id' => $group->id]) ?>" class="btn btn-danger delete-row"><i class="fa fa-trash"></i></a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            <?php endforeach ?>
                            </tbody>
                            <tfoot>
                            <th>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" id="check_all" style="cursor: pointer">
                                    </label>
                                </div>
                            </th>
                            <th>Название группы</th>
                            <th>Действия</th>
                            </tfoot>
                        </table>
                        <div id="actions" class="btn-group">
                            <button type="button" class="btn btn-default">Выполнить с выделенными</button>
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a data-action="delete" href="#">Удалить</a></li>
                            </ul>
                        </div>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->


    <!-- Форма отправки групповых действий -->
    <form id="action-form" action="<?= Url::to(['batch']) ?>" method="post">
        <input type="hidden" name="action">
        <input type="hidden" name="ids">
    </form>

<?php
$batchActionsUrl = Url::to();
$script = <<< JS
$("#example1").DataTable({
    "infoCallback": function( settings, start, end, max, total, pre ) {
        return "<div>" + pre + "</div>";
    },
    "columns": [
        { "orderable": false },
        { "orderable": true },
        { "orderable": false },
    ],
    "searching": false,
    "order": [[1, 'desc']],
    "language": {
        "lengthMenu": "Показать _MENU_ записей на странице",
        "zeroRecords": "Ничего не найдено",
        "info": "Показана _PAGE_ страница из _PAGES_",
        "infoEmpty": "Нет данных",
        "infoFiltered": "(отсортировано из _MAX_ записей)",
        "Search": "",
        "decimal":        "",
        "emptyTable":     "нет записей",
        "infoPostFix":    "",
        "thousands":      ",",
        "loadingRecords": "загрузка...",
        "processing":     "обработка...",
        "search":         "Поиск:",
        "paginate": {
            "first":      "Первый",
            "last":       "Последний",
            "next":       "Следующий",
            "previous":   "Предыдущий"
        },
        "aria": {
            "sortAscending":  ": activate to sort column ascending",
            "sortDescending": ": activate to sort column descending"
        }
    }
});
JS;

$this->registerJS($script, View::POS_READY);