common/models/User.php
<?php
namespace common\models;

use common\classes\OrderType;
use common\validators\NameValidator;
use common\validators\PhoneValidator;
use Yii;
use yii\db\ActiveRecord;
use yii\db\Query;
use yii\helpers\Url;
use yii\rbac\Role;
use yii\web\IdentityInterface;
use yii\base\Exception;
use common\notifications\Notification;

/**
 * User model
 *
 * @property integer            $id                     ID записи в базе данных
 * @property string             $firstname              Имя пользователя
 * @property string             $family                 Фамилия пользователя
 * @property string             $lastname               Отчество пользователя
 * @property string             $password               Пароль пользователя
 * @property string             $email                  Почта пользователя
 * @property integer            $created_at             Дата создания аккаунта
 * @property integer            $updated_at             Дата обновления аккаунта
 * @property Role               $role                   Роль пользователя
 * @property integer            $phone                  Телефон пользователя
 * @property integer            $profile_vk             Адрес профиля Vkontakte
 * @property integer            $profile_facebook       Адрес профиля Facebook
 * @property integer            $profile_google         Адрес профиля Google
 * @property integer            $profile_twitter        Адрес профиля Twitter
 * @property integer            $profile_mailru        Адрес профиля Twitter
 * @property string             $avatar                 Url аватара пользователя
 * @property string             $photo                  имя файла аватара пользователя
 * @property City               $city                   Город
 * @property int                $city_id                  ID Города
 * @property \DateTime          $birthday               День рождения
 * @property int                $has_ip                 Имеет ИП
 * @property int                $has_ul                 Имеет Юр.Лицо
 * @property int                $gender                 Имеет Юр.Лицо
 * @property string             $resume                 Резюме
 * @property string             $about                  О себе
 * @property string             $text                   какой-то текст
 * @property string             $status                 статус
 * @property int        $busyness               занятость
 * @property int        $confirmed_email        Подтвержден ли email
 * @property int        $confirmed_phone        Подтвержден ли телефон
 * @property array      $reviews                Отзывы о клиенте
 * @property array      $ordersTotalCount       Общее количество заказов
 * @property array      $rating                 Рейтинг
 * @property array      $orders                 Все заказы пользователя
 * @property NotificationsSettings              $notificationSettings   Настройки уведомлений
 * @property array      $notifications          Уведомления
 * @property array      $packages               Пакеты ползователя
 * @property array      $completedOrders        Завершенные работы
 * @property array      $completedOrdersCount   Количество завершенных работ
 * @property array      $registrationTermLabel   Времени зарегистрирован
 * @property array      $favorites              Избранные эксперты
 * @property array      $positiveReviews        Положительные отзывы
 * @property array      $negativeReviews        Негативные отзывы
 * @property int        $videos                 Видео пользователя
 * @property array      $groups                 Группы пользователя
 * @property int        $category_auto          Заказы категории 'авто'
 * @property int        $category_freight       Заказы категории 'грузовые'
 * @property int        $category_moto          Заказы категории 'мото'
 * @property int        $category_commerce      Заказы категории 'коммерческий'
 * @property int        $category_water         Заказы категории 'водный'
 * @property string     $profileUrl             Заказы категории 'водный'
 * @property string     $activation_key         Код активации аккаунта
 * @property string     $active                 Флаг, указывающий что аккаунт активирован
 * @property int        $card_id                ID карты
 * @property Card       $card                   Карта
 * @property UserDocument[]     $documents             Документы пользователя
 *
 */
class User extends ActiveRecord implements IdentityInterface
{
    const IS_ADMIN = 1;
    const IS_CLIENT = 2;
    const IS_EXPERT = 3;


    const SCENARIO_ADMIN_SAVE = 1;
    const SCENARIO_ADMIN_LOGIN = 2;


    const SCENARIO_CLIENT_SAVE = 3;
    const SCENARIO_CLIENT_SETTINGS = 4;

    const SCENARIO_EXPERT_SAVE = 5;
    const SCENARIO_EXPERT_SETTINGS = 6;
    const SCENARIO_EXPERT_INFO = 7;
    const SCENARIO_EXPERT_REGISTRATION = 8;

    const SCENARIO_LOGIN = 9;






    public $confirm;
    public $day;
    public $month;
    public $year;
    public $_groups;
    public $_role;



    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'users';
    }


    public function scenarios()
    {
        return [
            self::SCENARIO_LOGIN => ['login', 'password'],

            self::SCENARIO_ADMIN_LOGIN => ['email', 'password'],
            self::SCENARIO_ADMIN_SAVE => ['email', 'password', 'confirm', 'firstname', 'lastname', 'family', 'phone', '_role', 'profile_vk', 'profile_facebook', '_groups'],

            self::SCENARIO_CLIENT_SETTINGS => ['email', 'password', 'confirm', 'firstname', 'lastname', 'family', 'phone', '_role', 'gender', 'profile_vk', 'profile_facebook', 'has_ip', 'has_ul', '_groups'],

            self::SCENARIO_EXPERT_INFO => ['resume','about', 'status', 'text'],
            self::SCENARIO_EXPERT_SETTINGS => ['email', 'password', 'confirm', 'firstname', 'lastname', 'family', 'phone', '_role', 'gender', 'profile_vk', 'profile_facebook', 'has_ip', 'has_ul', '_groups'],
            self::SCENARIO_EXPERT_REGISTRATION => ['email', 'password', 'firstname', 'lastname', 'family', 'phone', 'avatar', 'activation_key', 'active', 'category_auto', 'category_freight', 'category_moto', 'category_commerce', 'category_water'],
        ];
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        $is_new_record = $this->getIsNewRecord();
        $saved = parent::save($runValidation, $attributeNames);
        if($saved && $is_new_record) {
            $settings = new NotificationsSettings(['user_id' => $this->id]);
            $settings->save(false);
        }
        return $saved;
    }


    /**
     * Активирует аккаунт
     *
     * @throws \yii\db\Exception
     */
    public function activate(){

        $this->activation_key = '';
        $this->active = 1;
        $this->save(false);

        $this->removeInactiveRecords();
    }


    /**
     * Если пользователь зарегистрировался, но не активировал аккаунт
     * и зарегистрировался повторно, создадутся 2 записи с одинаковым email,
     * которые можно активировать. Этот метод удаляет неактивные аккаунты с тем же email.
     *
     * @throws \yii\db\Exception
     */
    public function removeInactiveRecords()
    {
        \Yii::$app->db->createCommand()->delete(self::tableName(),[
            'email' => $this->email,
            'active' => 0
        ])->execute();
    }


    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [

            // SCENARIO_ADMIN_SAVE
            [['firstname', 'lastname', 'family', 'email', 'phone', 'password', 'confirm'], 'trim', 'on' => self::SCENARIO_ADMIN_SAVE],
            [['firstname'], 'required', 'message' => 'Введите имя', 'on' => self::SCENARIO_ADMIN_SAVE],
            [['lastname'], 'required', 'message' => 'Введите отчество', 'on' => self::SCENARIO_ADMIN_SAVE],
            [['family'], 'required', 'message' => 'Введите фамилию', 'on' => self::SCENARIO_ADMIN_SAVE],
            [['role_id'], 'required', 'message' => 'Необходимо задать роль пользователю', 'on' => self::SCENARIO_ADMIN_SAVE],
            [['email'], 'required', 'message' => 'Укажите email', 'on' => self::SCENARIO_ADMIN_SAVE],
            ['email', 'unique', 'targetClass' => User::class, 'targetAttribute' => 'email', 'filter' => 'id != ' . (int)$this->id, 'message' => 'Такой email занят', 'on' => self::SCENARIO_ADMIN_SAVE ],
            ['firstname', NameValidator::class, 'message' => 'Введите корректное имя'],
            ['family', NameValidator::class, 'message' => 'Введите корректную фамилию'],
            ['lastname', NameValidator::class, 'message' => 'Введите корректное отчество'],
            ['password', 'validatePasswordAdmin', 'skipOnEmpty' => false , 'on' => self::SCENARIO_ADMIN_SAVE ],
            [['role_id'], 'roleValidator', 'on' => self::SCENARIO_ADMIN_SAVE ],
            [['email'], 'email', 'message' => 'Неверный адрес почты', 'on' => self::SCENARIO_ADMIN_SAVE],
            ['phone', PhoneValidator::class , 'skipOnEmpty' => true , 'message' => 'Неверный формат номера', 'on' => self::SCENARIO_ADMIN_SAVE ],

            // SCENARIO_ADMIN_LOGIN
            [['email', 'password'], 'required', 'on' => self::SCENARIO_ADMIN_LOGIN ],

            // SCENARIO_LOGIN
            [['login', 'password'], 'required', 'on' => self::SCENARIO_LOGIN ],

            // SCENARIO_CLIENT_SETTINGS
            [['firstname', 'lastname', 'family'], 'string', 'on' => self::SCENARIO_CLIENT_SETTINGS],
            [['role_id', 'gender', 'has_ip', 'has_ul'], 'integer', 'on' => self::SCENARIO_CLIENT_SETTINGS ],
            [['has_ip', 'has_ul'], 'default', 'value' => 0, 'skipOnEmpty' => false, 'on' => self::SCENARIO_CLIENT_SETTINGS ],
            [['email'], 'email', 'on' => self::SCENARIO_CLIENT_SETTINGS],
            [['email'], 'required', 'on' => self::SCENARIO_CLIENT_SETTINGS ],

backend/controllers/UsersController.php
<?php
namespace backend\controllers;


use app\models\UsersSearch;
use common\models\City;
use common\models\Group;
use common\models\Role;
use common\models\User;
//use function GuzzleHttp\default_ca_bundle;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Yii;
use yii\db\Query;
use \yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\web\NotAcceptableHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\base\Exception;
use yii\web\View;

/**
 * Site controller
 */
class UsersController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['accessUsers'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['edit', 'delete', 'save', 'add', 'batch'],
                        'roles' => ['editUsers'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Страница "Список пользователей"
     *
     * @return string
     * @throws NotAcceptableHttpException
     */
    public function actionIndex(){

        $searchModel = new UsersSearch();
        $users = $searchModel->search(\Yii::$app->request->get());

        $cities = City::find()->all();
        $groups = Group::find()->all();
        $roles = \Yii::$app->authManager->getRoles();
        return $this->render('list', [
            'users' => $users,
            'searchModel' => $searchModel,
            'cities' => $cities,
            'groups' => $groups,
            'roles' => $roles,
        ]);
    }


    public function actionEdit($id){

        $user = User::findOne($id);

        if($user->can('Эксперт'))
            return $this->redirect(['/expert/settings', 'id' => $user->id]);
        if($user->can('Клиент'))
            return $this->redirect(['/client/settings', 'id' => $user->id]);

        $authManager = \Yii::$app->authManager;
        $roles = $authManager->getRoles();
        $userRole = $user->role;
        $userGroups = ArrayHelper::getColumn($user->groups, 'id');
        $groups = Group::find()->all();
        $socials = \Yii::$app->oauth->socials;
        return $this->render('edit', [
            'user' => $user,
            'roles' => $roles,
            'userRole' => $userRole,
            'userGroups' => $userGroups,
            'groups' => $groups,
            'socials' => $socials
        ]);
    }

    public function actionAdd(){
        $user = new User(['_role' => "Администратор"]);
        $authManager = \Yii::$app->authManager;
        $roles = $authManager->getRoles();
        $groups = Group::find()->all();
        $userRole = null;
        $userGroups = [];
        return $this->render('edit', [
            'user' => $user,
            'roles' => $roles,
            'userRole' => $userRole,
            'userGroups' => $userGroups,
            'groups' => $groups,
            'socials' => []
        ]);
    }

    public function actionDelete($id){

        try{
            if(!$user = User::findOne($id))
                throw new \Exception('Не найден пользователь');

            $user->delete();
            \Yii::$app->session->setFlash('operation-report', ['success' => true, 'message' => "Успешно удалено" ]);
        } catch(\Exception $e){
            \Yii::$app->session->setFlash('operation-report', ['success' => false, 'message' => $e->getMessage() ]);
        }

        return $this->redirect(['/users']);

    }

    /**
     * Сохранить пользователя
     *
     * @return string|Response
     * @throws NotFoundHttpException
     */
    public function actionSave(){

        if($id = Yii::$app->request->post('id')){
            if(!$user = User::findOne($id))
                throw new NotFoundHttpException("Не найден указанный пользователь");
        } else {
            $user = new User();
        }

        $user->scenario = User::SCENARIO_ADMIN_SAVE;
        $user->active = 1;
        if($user->load(Yii::$app->request->post(), '') && $user->save()){

            if($user->can('Клиент')) {
                $route = '/client/settings';
                $flashKey = 'client-settings';
            } elseif($user->can('Эксперт')) {
                $route = '/expert/settings';
                $flashKey = 'expert-settings';
            } else {
                $flashKey = 'user-settings';
                $route = '/users/edit';
            }

            $this->setFlash($flashKey, 'success', 'Пользователь сохранен');
            return $this->redirect([ $route , 'id' => $user->id]);
        }

        $authManager = \Yii::$app->authManager;
        $roles = $authManager->getRoles();
        $groups = Group::find()->all();
        $userRole = $user->role;
        $userGroups = ArrayHelper::getColumn($user->groups, 'id');

        if(\Yii::$app->user->identity->id == $user->id){
            $socials = \Yii::$app->oauth->socials;
        } else {
            $socials = [];
        }


        return $this->render('edit', [
            'user' => $user,
            'roles' => $roles,
            'userRole' => $userRole,
            'userGroups' => $userGroups,
            'groups' => $groups,
            'socials' => $socials
        ]);


        return $this->render('edit', ['user' => $user]);
    }

    private function setFlash($key,$status, $message){
        \Yii::$app->session->setFlash($key, [ 'status' => $status, 'message' => $message ]);
    }

    public function actionBatch(){

        $request = \Yii::$app->request;

        $ids = json_decode($request->post('ids'));
        $ids = array_map('intval', $ids);
        $action = $request->post('action');

        try{
            if($action == 'delete')
            {
                $users = User::findAll(['id' => $ids]);

                foreach($users as $user){
                    $user->delete();
                }

                \Yii::$app->session->setFlash('operation-report', ['success' => true, 'message' => "Пользователи удалены" ]);
            }

        } catch (Exception $e){
            \Yii::$app->session->setFlash('operation-report', ['success' => false, 'message' => $e->getMessage() ]);
        }

        return $this->redirect(['index']);
    }
}

backend/views/users/edit.php
<?php

/* @var $this yii\web\View */
/* @var $user \common\models\User */
/* @var $roles array */
/* @var $groups array */
/* @var $userRole \yii\rbac\Role */
/* @var $userGroups array */
/* @var $socials \common\interfaces\OauthInterface[] */

use yii\web\View;
use yii\helpers\Url;
use backend\assets\DateRangeAsset;
use backend\assets\InputmaskAsset;
use common\models\Role;
use common\models\Group;
use yii\helpers\ArrayHelper;

InputmaskAsset::register($this);
DateRangeAsset::register($this);

?>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        <?= $user->isNewRecord ? "Добавить пользователя" : "Редактировать пользователя" ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Главная</a></li>
        <li><a href="<?= Url::to(['users/index']) ?>">Пользователи</a></li>
        <li class="active"><?= $user->id ? "Редактировать учетную запись" : "Добавить пользователя" ?></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">

    <?php if($report = Yii::$app->session->getFlash('user-settings')): ?>
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4>	<i class="icon fa fa-check"></i> <?= $report['message'] ?></h4>
        </div>
    <?php endif; ?>

    <div class="box">
        <form class="form-horizontal" action="<?= Url::toRoute('/users/save') ?>" method="post">
            <input type="hidden" name="id" value="<?= $user->id ?>">
            <div class="box-body">

                    <div class="form-group">
                        <label for="inputFamily" class="col-sm-2 control-label">Фамилия</label>
                        <div class="col-sm-10">
                            <input name="family" id="inputFamily" type="text" class="form-control" placeholder="Введите фамилию" value="<?= $user->family ?>">
                        </div>
                    </div>
                    <?php if($user->hasErrors('family')): ?>
                    <div class="form-error"><?= $user->getFirstError('family') ?></div>
                    <?php endif; ?>
                    <div class="form-group">
                        <label for="inputFirstname" class="col-sm-2 control-label">Имя</label>
                        <div class="col-sm-10">
                            <input name="firstname" id="inputFirstname" type="text" class="form-control"placeholder="Введите имя" value="<?= $user->firstname ?>">
                        </div>
                    </div>
                    <?php if($user->hasErrors('firstname')): ?>
                    <div class="form-error"><?= $user->getFirstError('firstname') ?></div>
                    <?php endif; ?>
                    <div class="form-group">
                        <label for="inputLastname" class="col-sm-2 control-label">Отчество</label>
                        <div class="col-sm-10">
                            <input name="lastname" type="text" class="form-control" id="inputLastname" placeholder="Введите отчество" value="<?= $user->lastname ?>">
                        </div>
                    </div>
                    <?php if($user->hasErrors('lastname')): ?>
                    <div class="form-error"><?= $user->getFirstError('lastname') ?></div>
                    <?php endif; ?>
                    <div class="form-group">
                        <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                                <input name="email" id="inputEmail" type="email" class="form-control" placeholder="Email" value="<?= $user->email ?>">
                            </div>
                        </div>
                    </div>
                    <?php if($user->hasErrors('email')): ?>
                    <div class="form-error"><?= $user->getFirstError('email') ?></div>
                    <?php endif; ?>
                    <div class="form-group">
                        <label for="inputPhone" class="col-sm-2 control-label">Телефон</label>
                        <div class="col-sm-10">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-phone"></i>
                                </div>
                                <input name="phone" id="inputPhone" type="text" class="form-control" data-inputmask="&quot;mask&quot;: &quot;9 - (999) 999-9999&quot;" data-mask="" value="<?= $user->phone ?>">
                            </div>
                        </div>
                    </div>
                    <?php if($user->hasErrors('phone')): ?>
                        <div class="form-error"><?= $user->getFirstError('phone') ?></div>
                    <?php endif; ?>

                    <div class="form-group">
                        <label for="inputRole" class="col-sm-2 control-label">Роль</label>
                        <div class="col-sm-10">
                            <select name="_role" id="inputRole" class="form-control">
                                <?php foreach($roles as $role): /** @var $role \yii\rbac\Role */
                                    $selected = $role->name == $userRole ? ' selected' : '';
                                    echo "<option value=\"$role->name\"$selected>$role->name</option>";
                                endforeach; ?>
                            </select>
                        </div>
                    </div>



                    <div class="form-group">
                        <label for="inputGroups"  class="col-sm-2 control-label">Группы</label>
                        <div class="col-sm-10">
                            <select name="_groups[]" id="inputGroups" multiple class="form-control">
                                <?php
                                foreach($groups as $group): /** @var $group \common\models\Group */
                                    $selected = in_array($group->id, $userGroups) ? ' selected' : '';
                                    echo "<option value=\"$group->id\"$selected>$group->name</option>";
                                endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputPassword" class="col-sm-2 control-label">Пароль</label>
                        <div class="col-sm-10">
                            <input name="password" type="password" id="inputPassword" class="form-control" value="">
                        </div>
                    </div>
                    <?php if($user->hasErrors('password')): ?>
                    <div class="form-error"><?= $user->getFirstError('password') ?></div>
                    <?php endif; ?>
                    <div class="form-group">
                        <label for="inputConfirm" class="col-sm-2 control-label">Подтверждение</label>
                        <div class="col-sm-10">
                            <input name="confirm" id="inputConfirm" type="password" class="form-control" value="">
                        </div>
                    </div>


                <?php if(count($socials)) : ?>

                        <?php foreach($socials as $network):

                        if($network->name == 'mail.ru') continue;
                        $attribute = \common\models\User::networkAttribute($network->name)?>
                            <div class="form-group">
                                <label for="inputProfile_vk" class="col-sm-2 control-label">Профиль <?= $network->name ?></label>
                                <div class="col-sm-10">
                                <?php if($user->$attribute): ?>
                                    <a href="<?= Url::to(['/oauth/unlink', 'network' => $network->name ]) ?>" class="btn btn-success">Отвязать</a>
                                <?php else: ?>
                                    <a href="<?= Url::to(['/oauth/register', 'network' => $network->name]) ?>" class="btn btn-success">Привязать</a>
                                <?php endif; ?>
                                </div>
                            </div>
                        <?php endforeach; ?>

                <?php endif; ?>

            </div><!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-info">Сохранить</button>
            </div>
        </form>
    </div><!-- /.box -->

</section><!-- /.content -->


<?php

// плагины мешают SELENIUM вставлять в поля значения
if(!YII_ENV_TEST)
{

$script = <<< JS
//////////////////////////////////
// view: users/edit //////////////
//////////////////////////////////

$("[data-mask]").inputmask();

//Date range picker
$('#reservation').daterangepicker();
//////////////////////////////////

JS;
$this->registerJS($script, View::POS_READY);
}

backend/views/users/list-filter.php
<?php
/** @var $this \yii\web\View  */
/** @var $model \app\models\UsersSearch */

use yii\helpers\Url;
use common\models\City;
use common\models\Group;
use \common\models\Role;

?>


<div class="box">
    <form action="<?= Url::to(['users/index']) ?>" method="get">
    <div class="box-body">

        <div class="row">
            <div class="col-md-6">
                <!-- Date range -->
                <div class="form-group">
                    <label for="filter-registration">Регистрация</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <input name="registration" value="<?= $model->registration ?>" type="text" class="form-control pull-right" id="filter-registration" autocomplete="off">
                    </div><!-- /.input group -->
                </div><!-- /.form group -->

                <div class="form-group">
                    <label>Группы</label>
                    <select name="groups[]" multiple class="form-control">
                        <?php foreach($groups as $group) {
                            /** @var $group \common\models\Group */
                            $selected = in_array($group->id,$model->groups) ? "selected" : '';
                            echo "<option value='$group->id' $selected>$group->name</option>";
                        } ?>
                    </select>
                </div>
                <div class="form-group">
                    <label>Роль</label>
                    <select multiple name="roles[]" class="form-control">
                        <?php foreach($roles as $role) {
                            /** @var $role \yii\rbac\Role  */
                            $selected = in_array($role->name,$model->roles) ? "selected" : '';
                            echo "<option value='$role->name' $selected>$role->name</option>";
                        } ?>
                    </select>
                </div>

            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="filter-city">Город</label>
                    <select name="city" id="filter-city" class="form-control">
                        <option value="">Любой</option>
                        <?php foreach($cities as $city) {
                            /** @var $city \common\models\City */
                            $selected = $model->city == $city->id ? "selected" : "";
                            echo "<option value='$city->id' $selected >$city->name</option>";
                        } ?>
                    </select>
                </div>

                <!-- phone mask -->
                <div class="form-group">
                    <label for="filter-phone">Телефон:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-phone"></i>
                        </div>
                        <input name="phone" id="filter-phone" type="text" class="form-control" value="<?= $model->phone ?>" data-inputmask='"mask": "(999) 999-9999"' data-mask>
                    </div><!-- /.input group -->
                </div><!-- /.form group -->


                <div class="form-group">
                    <label for="filter-family">Фамилия</label>
                    <input name="family" type="text" class="form-control" id="filter-name" placeholder="Фамилия" value="<?= $model->family ?>">
                </div>

                <div class="form-group">
                    <label for="filter-firstname">Имя</label>
                    <input name="firstname" type="text" class="form-control" id="filter-name" placeholder="Имя" value="<?= $model->firstname ?>">
                </div>

                <div class="form-group">
                    <label for="filter-lastname">Отчество</label>
                    <input name="lastname" type="text" class="form-control" id="filter-name" placeholder="Отчество" value="<?= $model->lastname ?>">
                </div>

            </div>
        </div>

    </div><!-- /.box-body -->

    <div class="box-footer">
        <!--button type="reset" class="btn btn-default">Сбросить</button-->
        <button type="submit" class="btn btn-info pull-right">Применить</button>
    </div>

    </form>
</div><!-- /.box -->