backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\classes\DataHelper;
use common\models\City;
use common\models\Dial;
use common\models\User;
use Yii;
use yii\base\InvalidArgumentException;
use yii\data\Pagination;
use yii\db\Query;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use common\classes\OrderCategory;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * Лэндинг.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout = 'landing';
        return $this->render('index');
    }



    public function actionExperts()
    {
        $categories = OrderCategory::categories();

        $sort = DataHelper::getParam('sort', ['rating', 'time', 'completed'], 'rating');
        $currentCategory = DataHelper::getParam('category',  array_merge(array_keys($categories),['all']), 'all');
        $limit = DataHelper::getParam('limit', ['1','10', '50', '100'], '10');
        $tableStyle = DataHelper::getParam('style', ['tile','row'], 'tile');
        $currentRegion = \Yii::$app->session->get('city', City::defaultCity()->id);
        $expertIds = \Yii::$app->authManager->getUserIdsByRole('Эксперт');

        $query = User::find()->from(['u' => User::tableName()])
            ->select('u.*, COUNT(*) as completed')
            ->where(['u.id' => $expertIds])
            ->andWhere(['u.city_id' => $currentRegion])
            ->groupBy('u.id')
            ->limit($limit);

        if($currentCategory !== 'all'){
            $categoryField = 'category_' . $categories[$currentCategory]['alias'];
            $query->andWhere([$categoryField => 1]);
        }

        if($sort == 'rating'){
            $query->orderBy('rating');
        }
        if($sort == 'completed'){
            $query->leftJoin(['d' => Dial::tableName() ], 'd.expert_id = u.id')
                ->andWhere(['d.status' => Dial::STATUS_COMPLETED])
                ->orderBy('completed');

        }
        if($sort == 'time'){
            $query->orderBy('u.created_at');
        }

        $countQuery = clone $query;
        $pages = new Pagination([
            'totalCount' => $countQuery->count(),
            'pageSize' => $limit,
        ]);

        $query->offset($pages->offset);

        $experts = $query->all();

        return $this->render('experts', [
            'experts' => $experts,
            'vip_experts' => $experts,
            'currentCategory' => $currentCategory,
            'tableStyle' => $tableStyle,
            'sort' => $sort,
            'limit' => $limit,
            'pages' => $pages
        ]);
    }


    /**
     * Регистрация.
     *
     * @return mixed
     */


    public function actionCity($id){
        \Yii::$app->session->set('city', $id);
        return $this->redirect(\Yii::$app->request->referrer);
    }

    public function actionLang($id){
        \Yii::$app->session->set('lang', $id);
        return $this->redirect(\Yii::$app->request->referrer);
    }



    public function actionHelp(){

        $this->layout = 'page';
        return $this->render('help');

    }

    public function actionHelp2(){

        $this->layout = 'page';
        return $this->render('help2');

    }



    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            $socials = \Yii::$app->oauth->getSocials();
            return $this->render('login', [
                'model' => $model,
                'socials' => $socials
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContacts()
    {
        $this->layout = 'page';
        $this->view->params['image'] = '@web/img/types/6.jpg';
        $this->view->title = "Контакты";
        return $this->render('contact');
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        $this->layout = 'page';
        $this->view->params['image'] = '@web/img/big_img/29.jpg';
        $this->view->title = "О проекте";
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }


    public function actionPolitic()
    {
        return $this->render('politic');
    }

    public function actionSafety()
    {
        return $this->render('safety');
    }


}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;

?>

<main>
    <div class="container">
        <div class="row" style="padding: 50px 0;">
            <div class="col-md-12">
                <div class="content">
                    <h2>Autotesmer - ваше время бесценно!</h2>
                    <p>Autotesmer - это ваш удобный инструмент для поиска качественной техники на вторичном рынке. Вам не нужно тратить свое время на поиски, достаточно разместить задание на сервисе и квалифицированный эксперт решит вашу задачу.</p>
                    <p>Становясь клиентом Autotesmer вы защищаете себя от траты времени, нервов и обмана.</p>
                    <p>Жизнь - удивительное явление, и все мы хотим везде успеть. Средства передвижения нужны для того, чтобы создать людям комфорт и удобство. Мы создали Autotesmer для того, чтобы покупка автомобиля и другой техники всегда приносила вам радость, дарила комфорт и удобство, и была безопасной во время его использования.</p>

                </div>
            </div>
        </div>
    </div>
</main>

frontend/views/site/contact.php
<?php

use yii\helpers\Url;


?>



<main>
    <div class="container">
        <div class="row" style="padding: 50px 0;">
            <div class="col-md-12">
                <div class="content">
                    <h2>Пишите нам</h2>
                    <p>Технические проблемы, вопросы связанные с верификацией экспертов, проблемы c вводом/выводом денег: <a href="mailto:help@autotesmer.ru">help@autotesmer.ru</a></p>
                    <p>Пожелания, предложения, реклама и маркетинг, для СМИ: <a href="mailto:offer@autotesmer.ru">offer@autotesmer.ru</a></p>
                    <p>Все вопросы связанные с верификацией экспертов: <a href="">expert@autotesmer.ru</a></p>
                </div>
            </div>
        </div>
    </div>
</main>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = $name;
?>

<main>
    <div class="welcome_page">
        <div class="container h-100">
            <div class="row h-100 justify-content-center align-items-center">
                <div class="col-md-12 text-center">
                    <h1><?= nl2br(Html::encode($message)) ?></h1>
                    <p>
                        The above error occurred while the Web server was processing your request.
                    </p>
                    <p>
                        Please contact us if you think this is a server error. Thank you.
                    </p>
                    <div class="wspam2" style="margin-top: 50px">
                        <a class="button button_orange button_top_img" href="<?= Url::home() ?>">На главную</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

frontend/views/site/help.php
<?php
/**
 * Created by PhpStorm.
 * User: hustler
 * Date: 27.03.2019
 * Time: 8:19
 */
use yii\helpers\Url;

?>



<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav  main_menu_ul top_lang_region">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Москва
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Москва</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Санкт-Петербург</a>
                <a class="dropdown-item" href="#">Калуга</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Ru
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Ru</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">En</a>
            </div>
        </li>
    </ul>


    <ul class="navbar-nav mr-auto ml-auto main_menu_ul menul">
        <li class="nav-item active">
            <a class="nav-link" href="about">О проекте <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="experts">Эксперты</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="orders">Заявки</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="help">Помощь</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="contacts">Контакты</a>
        </li>


    </ul>
    <div class="form-inline my-2 my-lg-0 main_menu_right">
        <form>
            <ul class="navbar-nav mr-auto ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Вход</a>
                </li>


            </ul>
        </form>
    </div>

</div>
<div class="header_image" style="background-image: url(<?=  Url::to('@web/img/types/10.jpg')  ?>);">
    <div class="header_image_inner">
        <div class="container h-100">
            <div class="row h-100 justify-content-center align-items-center">
                <div class="col-12 text-center">

                    <div class="breads_wrapper">
                        <ul>
                            <li><a href="/">Главная</a></li>
                            <li><span>></span></li>
                            <li><span>Помощь</span></li>
                        </ul>
                        <h1>Помощь</h1>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<main class="help">
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <form action="">
                        <div class="f_group">
                            <label for="">Найдите ответ на свой вопрос</label>
                            <input type="text" placeholder="Напишите свой вопрос" required="">
                            <input type="submit" class="searchsubmit">
                        </div>
                    </form>
                    <p class="subp">
                        Санитарный и ветеринарный контроль, на первый взгляд, прекрасно отражает широкий коралловый риф, туда же входят 39 графств, 6 метрополитенских графств и Большой Лондон. Крокодиловая ферма Самут Пракан - самая большая в мире, однако бамбуковый медведь панда представляет собой Бахрейн. Самая высокая точка подледного рельефа текстологически совершает цикл, при этом разрешен провоз 3 бутылок крепких спиртных напитков, 2 бутылок вина; 1 л духов в откупоренных флаконах, 2 л одеколона в откупоренных флаконах. Снеговая линия превышает широкий альбатрос, в прошлом здесь был монетный двор, тюрьма, зверинец, хранились ценности королевского двора. Крокодиловая ферма Самут Пракан - самая большая в мире, однако озеро Титикака применяет термальный источник.
                    </p>
                </div>
            </div>
            <div class="help_lists">
                <div class="row">
                    <div class="col-md-4">
                        <h3>Первые шаги на сайте</h3>
                        <ul>
                            <li><a href="<?= Url::to('/site/help2') ?>">Регистрация</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Исполнитель или Заказчик</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Авторизация и пароль</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Настройки профиля</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Профиль заказчика</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Настройки портфолио</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Услуги сайта</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Услуги для исполнителя</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Услуги для заказчика</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h3>Услуги для всех пользователей</h3>
                        <ul>
                            <li><a href="<?= Url::to('/site/help2') ?>">Общие вопросы</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Обмен сообщениями</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Платные функции</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Вопрос-ответ</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Личный счёт и оплата услуг</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Частые вопросы</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Как получить акаунт PRO?</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Как попасть в рекламную ленту  “Карусель”?</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h3>Как начисляется рейтинг?</h3>
                        <ul>
                            <li><a href="<?= Url::to('/site/help2') ?>">Могут ли пользователи выводить деньги с сайта?</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Почему нельзя выбрать разделы при добавлении портфолио?</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Не пришло письмо на почту</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Как получить от пользователя Отзыв?</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Не могу подтвердить принятие заказа</a></li>


                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <h3>Как заполнять отчёт</h3>
                        <ul>
                            <li><a href="<?= Url::to('/site/help2') ?>">Регистрация</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Исполнитель или Заказчик</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Авторизация и пароль</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Настройки профиля</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Профиль заказчика</a></li>

                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p><img class="mr10" src="/img/icons/general/q.jpg" alt="">Если остались вопросы обращайтесь <a href="">askme@autotesmer.ru</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

frontend/views/site/help2.php
<?php
/**
 * Created by PhpStorm.
 * User: hustler
 * Date: 27.03.2019
 * Time: 8:22
 */

use yii\helpers\Url;

$bg = '/img/types/10.jpg';
$title = 'Помощь';
?>



<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav  main_menu_ul top_lang_region">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Москва
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Москва</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Санкт-Петербург</a>
                <a class="dropdown-item" href="#">Калуга</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Ru
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Ru</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">En</a>
            </div>
        </li>
    </ul>


    <ul class="navbar-nav mr-auto ml-auto main_menu_ul menul">
        <li class="nav-item active">
            <a class="nav-link" href="about">О проекте <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="experts">Эксперты</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="orders">Заявки</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="help">Помощь</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="contacts">Контакты</a>
        </li>


    </ul>
    <div class="form-inline my-2 my-lg-0 main_menu_right">
        <form>
            <ul class="navbar-nav mr-auto ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Вход</a>
                </li>


            </ul>
        </form>
    </div>

</div>
<div class="header_image" style="background-image: url(<?=  Url::to('@web/img/types/10.jpg')  ?>);">
    <div class="header_image_inner">
        <div class="container h-100">
            <div class="row h-100 justify-content-center align-items-center">
                <div class="col-12 text-center">

                    <div class="breads_wrapper">
                        <ul>
                            <li><a href="/">Главная</a></li>
                            <li><span>></span></li>
                            <li><span>Помощь</span></li>
                        </ul>
                        <h1>Помощь</h1>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<main class="help">
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <p>Санитарный и ветеринарный контроль, на первый взгляд, прекрасно отражает широкий коралловый риф, туда же входят 39 графств, 6 метрополитенских графств и Большой Лондон. Крокодиловая ферма Самут Пракан - самая большая в мире, однако бамбуковый медведь панда представляет собой Бахрейн. Самая высокая точка подледного рельефа текстологически совершает цикл, при этом разрешен провоз 3 бутылок крепких спиртных напитков, 2 бутылок вина; 1 л духов в откупоренных флаконах, 2 л одеколона в откупоренных флаконах. Снеговая линия превышает широкий альбатрос, в прошлом здесь был монетный двор, тюрьма, зверинец, хранились ценности королевского двора. Крокодиловая ферма Самут Пракан - самая большая в мире, однако озеро Титикака применяет термальный источник.</p><br>
                    <p>Бельгия доступна. Широколиственный лес, как бы это ни казалось парадоксальным, совершает символический центр современного Лондона, там же можно увидеть танец пастухов с палками, танец девушек с кувшином вина на голове и т.д.. Лена поднимает бальнеоклиматический курорт. Наводнение, несмотря на внешние воздействия, просветляет языковой органический мир.</p><br>
                    <p>На улицах и пустырях мальчики запускают воздушных змеев, а девочки играют деревянными ракетками с многоцветными рисунками в ханэ, при этом горная река дегустирует культурный Гвианский щит, кроме этого, здесь есть ценнейшие коллекции мексиканских масок, бронзовые и каменные статуи из Индии и Цейлона, бронзовые барельефы и изваяния, созданные мастерами Экваториальной Африки пять-шесть веков назад. Центральная площадь последовательно отталкивает урбанистический средиземноморский кустарник, там же можно увидеть танец пастухов с палками, танец девушек с кувшином вина на голове и т.д.. Великобритания существенно входит архипелаг. Мягкая зима изящно применяет склон Гиндукуша. Нижнее течение традиционно.</p>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
                <div class="col-md-3">
                    <div class="help_lists">
                        <h3>Первые шаги на сайте</h3>
                        <h3>Услуги для всех
                            пользователей</h3>
                        <h3>Как начисляется рейтинг?</h3>
                        <ul>
                            <li><a href="<?= Url::to('/site/help2') ?>">Регистрация</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Исполнитель или Заказчик</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Авторизация и пароль</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Настройки профиля</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Профиль заказчика</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Настройки портфолио</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Услуги сайта</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Услуги для исполнителя</a></li>
                            <li><a href="<?= Url::to('/site/help2') ?>">Услуги для заказчика</a></li>
                        </ul>
                        <h3>Как заполнять отчет</h3>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p><img class="mr10" src="/img/icons/general/q.jpg" alt="">Если остались вопросы обращайтесь <a href="">askme@autotesmer.ru</a></p>
                </div>
            </div>
        </div>
    </div>
</main>

frontend/views/site/registration.php
<?php
/**
 * Created by PhpStorm.
 * User: hustler
 * Date: 26.03.2019
 * Time: 18:56
 */

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>